; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = code

[env:m5stick-c]
platform = espressif32@6.12.0
board = m5stick-c
framework = arduino
board_build.partitions = no_ota.csv
build_flags =
    -Os                          ; Optimize for size
    -DCORE_DEBUG_LEVEL=0         ; Disable debug output
    -DBOARD_HAS_PSRAM=0          ; Disable PSRAM for M5Stick-C
    -ffunction-sections          ; Enable dead code elimination
    -fdata-sections              ; Enable dead data elimination
    -Wl,--gc-sections            ; Enable garbage collection of unused sections
    -DARDUINO_USB_CDC_ON_BOOT=0  ; Disable USB CDC
    -DARDUINO_USB_MSC_ON_BOOT=0  ; Disable USB MSC
    -DARDUINO_USB_DFU_ON_BOOT=0  ; Disable USB DFU
lib_deps =
	m5stack/M5StickCPlus2@^1.0.2
	m5stack/M5Unified@^0.2.7
	https://github.com/pschatzmann/ESP32-A2DP.git
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/jcarletto27/M5MicPeakRMS.git
	https://github.com/jcarletto27/ESP32-BT-Scanner.git

